const userSkills = {
  ProgrammingLanguages: [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "C",
    "PHP",
    "Ruby",
    "Go",
  ],
  SystemDesign: [
    "GraphQL",
    "REST",
    "SOAP",
    "RPC",
    "Microservices",
    "Event-Driven Architecture",
    "Message Brokers",
    "API Gateways",
    "Load Balancers",
    "Caching",
  ],
  Frontend: [
    "React",
    "Angular",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Remix",
    "SolidJS",
  ],
  Backend: [
    "Node.js",
    "Express",
    "Fastify",
    "NestJS",
    "Spring Boot",
    "Laravel",
    "Django",
  ],
  DevOps: ["Docker", "Kubernetes", "CI/CD", "DevOps", "Agile"],
  Operations: [
    "AWS",
    "Azure",
    "GCP",
    "Heroku",
    "Cloudflare",
    "DigitalOcean",
    "Vercel",
    "Netlify",
  ],
};
